port: 7880
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  # Für Produktion: use_external_ip: true und external_ip setzen

# Redis für Cluster-Support und State Management
redis:
  address: redis:6379
  password: ${LIVEKIT_REDIS_PASSWORD}
  db: 0

# Webhook für Event-Handling
webhook:
  urls:
    - http://backend:8000/api/webhooks/livekit
  api_key: ${LIVEKIT_API_KEY}

# Sicherheitseinstellungen
room:
  # Automatisches Löschen leerer Räume nach 5 Minuten
  empty_timeout: 300
  # Maximale Teilnehmerzahl pro Raum
  max_participants: 20
  # Aktiviere E2E Verschlüsselung
  enable_e2e_encryption: true

# Audio/Video Qualitätseinstellungen
audio:
  # Opus codec für beste Qualität
  default_codec: opus
  # Echo cancellation und noise suppression
  echo_cancellation: true
  noise_suppression: true
  auto_gain_control: true

video:
  # VP9 für bessere Kompression
  default_codec: vp9
  # HD als Standard
  default_resolution: 1280x720
  # Adaptive Bitrate
  min_bitrate: 400000
  max_bitrate: 2500000

# Aufzeichnung (Recording)
recording:
  # Aufzeichnungen werden lokal gespeichert
  file_output:
    local: true
    path: /recordings
  # Segmentierung für große Aufzeichnungen
  segment_duration: 3600 # 1 Stunde

# Logging für Audit Trail
logging:
  level: info
  # Strukturiertes JSON Logging für bessere Auswertung
  json: true
  # Sample rate für Performance
  sample: 1.0

# API Keys werden über Umgebungsvariablen gesetzt
keys:
  ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}

# Limits für Sicherheit
limits:
  # Max. Bitrate pro Teilnehmer
  max_bitrate: 3000000
  # Max. Video Layers
  max_video_layers: 3
  # Max. Tracks pro Teilnehmer
  max_tracks_per_participant: 10

# TURN Server Konfiguration für NAT Traversal
turn:
  enabled: true
  # Domain für TLS
  domain: ${TURN_DOMAIN}
  # TLS Port
  tls_port: 5349
  # UDP Port  
  udp_port: 3478
  # Externe IPs für TURN
  external_tls: true 