[build]
  base = "frontend/heydok-video-frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"

# Wichtig für React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers für Sicherheit
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(*), microphone=(*), display-capture=(*)" 