# LiveKit Development Configuration
port: 7880
bind_addresses:
  - ""

# API Key Configuration
keys:
  devkey: secret

# WebRTC Configuration
rtc:
  tcp_port: 7881
  port_range_start: 50000
  port_range_end: 60000
  use_external_ip: false
  node_ip: "0.0.0.0"

# Room Configuration
room:
  auto_create: true
  enable_recording: false
  empty_timeout: 300s  # 5 minutes
  departure_timeout: 20s

# Development Settings
development: true
log_level: debug

# TURN Server (disabled for development)
turn:
  enabled: false

# Recording (disabled for development)
recording:
  enabled: false

# Webhook (disabled for development)
webhook:
  urls: []

# Redis (optional for clustering)
redis:
  address: "redis:6379"
  db: 0 